# Generated by Django 2.1.7 on 2019-03-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32, verbose_name='班级名称')),
                ('class_type', models.CharField(default='高中', max_length=32, verbose_name='年级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.NullBooleanField(verbose_name='性别')),
                ('student_tel', models.CharField(max_length=15, verbose_name='学生电话')),
                ('register_date', models.DateField(verbose_name='注册时间')),
                ('student_type', models.CharField(max_length=10, verbose_name='生源类型')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证')),
                ('location_of_household_registration', models.CharField(max_length=128, verbose_name='户口性质')),
                ('tel_two', models.CharField(max_length=15, verbose_name='第二联系人')),
                ('major', models.CharField(max_length=32, verbose_name='专业')),
                ('address', models.CharField(max_length=128, verbose_name='现居住地')),
                ('status', models.CharField(max_length=12, verbose_name='学生状态')),
                ('market', models.CharField(max_length=1024, verbose_name='备注')),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolManage.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=32, verbose_name='姓名')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='m',
            field=models.ManyToManyField(to='SchoolManage.Teacher'),
        ),
    ]
